# Default-Logindaten. Wenn andere Daten lokal
# genutzt werden sollen, dann bitte diese 8 Zeilen
# in eine Datei dblogin.yml kopieren und dort die
# eigenen Daten angeben.
# Bitte die dblogin.yml NICHT in dei Versionskontrolle einchecken!
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: tippspiel_development_em2016 #tippspiel_development_wm2014

test:
  <<: *default
  database: tippspiel_test

# prod db == dev db
production:
  <<: *default
  database: tippspiel_development_em2016 # hier nutzen wir auch lokal unser dev DB