default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: tippspiel_development_wm2018

test:
  <<: *default
  database: tippspiel_test

# prod db == dev db
production:
  <<: *default
  database: tippspiel_development_wm2018 # hier nutzen wir auch lokal unser dev DB